version: '3.3'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springcloud
      MYSQL_USER: eric
      MYSQL_PASSWORD: admin
    networks:
      - persist
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - persist
volumes:
  db_data: {}
  redis-data: {}
networks:
  persist: {}
