server:
  port: 7004
  servlet:
    context-path: /coupon-permission
spring:
  application:
    name: eureka-client-coupon-permission
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: eric
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: couponHikariCP
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/