server:
  port: 7002
  servlet:
    context-path: /coupon-distribution
spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      properties:
        hibernate.show_sql: true
        hibernate.format_sql: true
      open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: eric
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: couponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      group-id: spring-coupon-x
      auto-offset-reset: latest
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    com.spring.coupon: debug
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
      eureka-client-coupon-template:
        connectTimeout: 3000
        readTimeout: 5000
